import Head from 'next/head';
import Box from "@mui/material/Box";
import LoginForm from "@/components/Login/LoginForm";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box component={'main'} sx={{height: '100vh', display: 'flex', justifyContent: 'center', alignItems: 'center'}}>
        <LoginForm/>
      </Box>
    </>
  )
}
